-- DB Lens PostgreSQL fixtures.
--
-- Mirrors fixtures/make.mjs so the same behaviours can be exercised against a
-- server: identity and composite primary keys, a foreign key, a view, a table
-- with no primary key at all (read-only), a bigint that overflows a JS number,
-- bytea, timestamps and nulls.
--
-- Applied by fixtures/postgres.mjs, which starts the container first.

DROP VIEW IF EXISTS v_order_totals;
DROP TABLE IF EXISTS order_lines, orders, customers, settings, audit_log CASCADE;

CREATE TABLE customers (
  id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    text NOT NULL,
  email   text UNIQUE,
  age     integer,
  joined  date,
  balance numeric(12, 2),
  big_id  bigint,
  avatar  bytea,
  notes   text
);
CREATE INDEX ix_customers_age ON customers (age);

CREATE TABLE orders (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
  sku         text NOT NULL,
  qty         integer NOT NULL,
  unit_price  numeric(10, 2) NOT NULL,
  placed_at   timestamptz NOT NULL,
  status      text NOT NULL
);
CREATE INDEX ix_orders_customer ON orders (customer_id);

CREATE TABLE order_lines (
  order_id bigint NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  line_no  integer NOT NULL,
  sku      text NOT NULL,
  qty      integer NOT NULL,
  PRIMARY KEY (order_id, line_no)
);

CREATE TABLE settings (
  key   text PRIMARY KEY,
  value text
);

-- No primary key, so there is no way to address a row: must be read-only.
CREATE TABLE audit_log (
  message text,
  at      timestamptz
);

CREATE VIEW v_order_totals AS
  SELECT o.id            AS order_id,
         c.name          AS customer,
         o.status        AS status,
         (o.qty * o.unit_price)::numeric(12, 2) AS total
  FROM orders o
  JOIN customers c ON c.id = o.customer_id;

-- Deterministic data: setseed makes random() reproducible for this session.
SELECT setseed(0.42);

INSERT INTO customers (name, email, age, joined, balance, big_id, avatar, notes)
SELECT
  (ARRAY['Ada','Grace','Alan','Katherine','Linus','Barbara','Ken','Margaret',
         'Dennis','Radia','Anita','Edsger','Frances','Donald','Jean','Vint'])
    [1 + floor(random() * 16)::int]
  || ' ' ||
  (ARRAY['Lovelace','Hopper','Turing','Johnson','Torvalds','Liskov','Thompson',
         'Hamilton','Ritchie','Perlman','Borg','Dijkstra','Allen','Knuth','Bartik','Cerf'])
    [1 + floor(random() * 16)::int],
  'user' || g || '@example.com',
  CASE WHEN random() < 0.06 THEN NULL ELSE 21 + floor(random() * 52)::int END,
  DATE '2010-01-01' + floor(random() * 5500)::int,
  round((random() * 90000)::numeric, 2),
  -- Beyond Number.MAX_SAFE_INTEGER for every 97th row, to prove int8 precision.
  CASE WHEN g % 97 = 0 THEN 9007199254740991::bigint + g ELSE g * 7 END,
  CASE WHEN g % 50 = 0 THEN decode('89504e470d0a1a0a', 'hex') ELSE NULL END,
  CASE WHEN g % 11 = 0 THEN 'Repeat customer — flagged for a follow-up call.' ELSE NULL END
FROM generate_series(1, 5000) g;

INSERT INTO orders (customer_id, sku, qty, unit_price, placed_at, status)
SELECT
  1 + floor(random() * 5000)::int,
  (ARRAY['BLT-01','DRL-07','HSK-12','LMN-33','NUT-04'])[1 + floor(random() * 5)::int],
  1 + floor(random() * 40)::int,
  round((random() * 24000)::numeric, 2) / 100,
  TIMESTAMPTZ '2026-01-01 00:00:00+00' + (floor(random() * 260) * INTERVAL '1 day'),
  (ARRAY['pending','shipped','delivered','refunded','cancelled'])[1 + floor(random() * 5)::int]
FROM generate_series(1, 12000) g;

INSERT INTO order_lines (order_id, line_no, sku, qty)
SELECT o, l, (ARRAY['BLT-01','DRL-07','HSK-12','LMN-33','NUT-04'])[1 + floor(random() * 5)::int],
       1 + floor(random() * 12)::int
FROM generate_series(1, 12000) o
CROSS JOIN LATERAL generate_series(1, 1 + (o % 4)) l
WHERE o % 4 = 0;

INSERT INTO settings (key, value) VALUES
  ('currency', 'USD'),
  ('timezone', 'America/New_York'),
  ('theme', 'dark'),
  ('retention_days', '365'),
  ('last_export', NULL);

INSERT INTO audit_log (message, at)
SELECT 'audit entry ' || g, TIMESTAMPTZ '2026-02-01 00:00:00+00' + (g * INTERVAL '1 hour')
FROM generate_series(1, 12) g;

ANALYZE;
