-- DB Lens PostgreSQL fixtures.
--
-- Mirrors fixtures/make.mjs so the same behaviours can be exercised against a
-- server: identity and composite primary keys, a foreign key, a view, a table
-- with no primary key at all (read-only), a bigint that overflows a JS number,
-- bytea, timestamps and nulls.
--
-- Applied by fixtures/postgres.mjs, which starts the container first.

-- Everything this file creates is dropped first, so it can be re-applied to an
-- existing database without a half-finished seed.
DROP VIEW IF EXISTS v_order_totals;
DROP TABLE IF EXISTS order_lines, orders, customers, settings, audit_log CASCADE;
DROP TABLE IF EXISTS public.events, public.odd_types, public.edge_keys CASCADE;
DROP TABLE IF EXISTS public."weird ""quoted"" name" CASCADE;
DROP TABLE IF EXISTS analytics.events CASCADE;

CREATE TABLE customers (
  id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    text NOT NULL,
  email   text UNIQUE,
  age     integer,
  joined  date,
  balance numeric(12, 2),
  big_id  bigint,
  avatar  bytea,
  notes   text
);
CREATE INDEX ix_customers_age ON customers (age);

CREATE TABLE orders (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
  sku         text NOT NULL,
  qty         integer NOT NULL,
  unit_price  numeric(10, 2) NOT NULL,
  placed_at   timestamptz NOT NULL,
  status      text NOT NULL
);
CREATE INDEX ix_orders_customer ON orders (customer_id);

CREATE TABLE order_lines (
  order_id bigint NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  line_no  integer NOT NULL,
  sku      text NOT NULL,
  qty      integer NOT NULL,
  PRIMARY KEY (order_id, line_no)
);

CREATE TABLE settings (
  key   text PRIMARY KEY,
  value text
);

-- No primary key, so there is no way to address a row: must be read-only.
CREATE TABLE audit_log (
  message text,
  at      timestamptz
);

CREATE VIEW v_order_totals AS
  SELECT o.id            AS order_id,
         c.name          AS customer,
         o.status        AS status,
         (o.qty * o.unit_price)::numeric(12, 2) AS total
  FROM orders o
  JOIN customers c ON c.id = o.customer_id;

-- Deterministic data: setseed makes random() reproducible for this session.
SELECT setseed(0.42);

INSERT INTO customers (name, email, age, joined, balance, big_id, avatar, notes)
SELECT
  (ARRAY['Ada','Grace','Alan','Katherine','Linus','Barbara','Ken','Margaret',
         'Dennis','Radia','Anita','Edsger','Frances','Donald','Jean','Vint'])
    [1 + floor(random() * 16)::int]
  || ' ' ||
  (ARRAY['Lovelace','Hopper','Turing','Johnson','Torvalds','Liskov','Thompson',
         'Hamilton','Ritchie','Perlman','Borg','Dijkstra','Allen','Knuth','Bartik','Cerf'])
    [1 + floor(random() * 16)::int],
  'user' || g || '@example.com',
  CASE WHEN random() < 0.06 THEN NULL ELSE 21 + floor(random() * 52)::int END,
  DATE '2010-01-01' + floor(random() * 5500)::int,
  round((random() * 90000)::numeric, 2),
  -- Beyond Number.MAX_SAFE_INTEGER for every 97th row, to prove int8 precision.
  CASE WHEN g % 97 = 0 THEN 9007199254740991::bigint + g ELSE g * 7 END,
  CASE WHEN g % 50 = 0 THEN decode('89504e470d0a1a0a', 'hex') ELSE NULL END,
  CASE WHEN g % 11 = 0 THEN 'Repeat customer — flagged for a follow-up call.' ELSE NULL END
FROM generate_series(1, 5000) g;

INSERT INTO orders (customer_id, sku, qty, unit_price, placed_at, status)
SELECT
  1 + floor(random() * 5000)::int,
  (ARRAY['BLT-01','DRL-07','HSK-12','LMN-33','NUT-04'])[1 + floor(random() * 5)::int],
  1 + floor(random() * 40)::int,
  round((random() * 24000)::numeric, 2) / 100,
  TIMESTAMPTZ '2026-01-01 00:00:00+00' + (floor(random() * 260) * INTERVAL '1 day'),
  (ARRAY['pending','shipped','delivered','refunded','cancelled'])[1 + floor(random() * 5)::int]
FROM generate_series(1, 12000) g;

INSERT INTO order_lines (order_id, line_no, sku, qty)
SELECT o, l, (ARRAY['BLT-01','DRL-07','HSK-12','LMN-33','NUT-04'])[1 + floor(random() * 5)::int],
       1 + floor(random() * 12)::int
FROM generate_series(1, 12000) o
CROSS JOIN LATERAL generate_series(1, 1 + (o % 4)) l
WHERE o % 4 = 0;

INSERT INTO settings (key, value) VALUES
  ('currency', 'USD'),
  ('timezone', 'America/New_York'),
  ('theme', 'dark'),
  ('retention_days', '365'),
  ('last_export', NULL);

INSERT INTO audit_log (message, at)
SELECT 'audit entry ' || g, TIMESTAMPTZ '2026-02-01 00:00:00+00' + (g * INTERVAL '1 hour')
FROM generate_series(1, 12) g;

-- A second schema, plus a table of the same name in each, so object
-- resolution has to disambiguate rather than guess.
CREATE SCHEMA IF NOT EXISTS analytics;

DROP TABLE IF EXISTS analytics.events;
CREATE TABLE analytics.events (
  id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  at   timestamptz
);
INSERT INTO analytics.events (name, at)
SELECT 'evt-' || g, TIMESTAMPTZ '2026-03-01 00:00:00+00' + (g * INTERVAL '1 minute')
FROM generate_series(1, 40) g;

CREATE TABLE public.events (
  id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note text
);
INSERT INTO public.events (note) SELECT 'public-' || g FROM generate_series(1, 5) g;

-- Types the grid has to render, and two it must refuse to write.
DROP TABLE IF EXISTS public.odd_types;
CREATE TABLE public.odd_types (
  id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payload bytea,
  doc     jsonb,
  tags    text[],
  flag    boolean,
  ident   uuid,
  span    interval,
  amount  numeric(30, 10)
);
INSERT INTO public.odd_types (payload, doc, tags, flag, ident, span, amount) VALUES
  (decode('deadbeef', 'hex'), '{"a":1,"b":[2,3]}', ARRAY['x','y'], true,
   '11111111-2222-3333-4444-555555555555', '1 day 02:03:04', 12345678901234567890.1234567890),
  (NULL, NULL, NULL, false, NULL, NULL, NULL);

-- Composite key, to exercise key binding beyond a single column.
DROP TABLE IF EXISTS public.edge_keys;
CREATE TABLE public.edge_keys (a text, b text, v text, PRIMARY KEY (a, b));
INSERT INTO public.edge_keys VALUES ('x', 'y', 'first'), ('x', 'z', 'second');

-- An identifier that needs quoting to survive.
DROP TABLE IF EXISTS public."weird ""quoted"" name";
CREATE TABLE public."weird ""quoted"" name" (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "col ""x""" text
);
INSERT INTO public."weird ""quoted"" name" ("col ""x""") VALUES ('quoted-value');

ANALYZE;
